version: '3.8'

services:
  api:
    build:
      target: build-deps
    environment:
      - NODE_ENV=development
    volumes:
      - ./src:/app/src
      - ./package.json:/app/package.json
      - ./tsconfig.json:/app/tsconfig.json
      - api_data:/app/data
    command: ["npm", "run", "dev"]
    ports:
      - "6000:6000"
      - "9229:9229"  # Debug port

  worker:
    build:
      target: build-deps
    environment:
      - NODE_ENV=development
    volumes:
      - ./src:/app/src
      - ./package.json:/app/package.json
      - ./tsconfig.json:/app/tsconfig.json
      - api_data:/app/data
    command: ["npm", "run", "worker"]

  # Redis Commander for development
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: event-reminder-redis-ui
    restart: unless-stopped
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8082:8082"
    depends_on:
      - redis